abak-press/sphinx-integration

lib/sphinx/integration/server_pool.rb
lib/sphinx/integration/version.rb

https://jira.railsc.ru/browse/BPC-11892

feature: log error message when error on server

---

lib/sphinx/integration/statements/rt.rb
spec/sphinx/integration/statements/rt_spec.rb

https://jira.railsc.ru/browse/BPC-12928
Это мне нужно для измерения профита и собственно это в будущем будет весьма полезным изменением.

feature: allow to replace method send batches

---

lib/sphinx/integration/transmitter.rb
spec/sphinx/integration/transmitter_spec.rb

Это первая часть.
Коммит позволит пачкой засылать в REPLACE INTO
https://jira.railsc.ru/browse/BPC-12928

feature: allow to replace by batches

---

lib/sphinx/integration/extensions/thinking_sphinx/active_record.rb
lib/sphinx/integration/extensions/thinking_sphinx/index.rb
lib/sphinx/integration/transmitter.rb
spec/spec_helper.rb
spec/sphinx/integration/extensions/thinking_sphinx/active_record_spec.rb
spec/sphinx/integration/transmitter_spec.rb
sphinx-integration.gemspec

https://jira.railsc.ru/browse/BPC-12928
Предоставит методы для пачечного `transmiter_update`'а и ``transmiter_destroy`'я

feature: conditional transmitter_update and transmitter_destroy

---

lib/sphinx/integration.rb
lib/sphinx/integration/buffered_transmitter.rb
lib/sphinx/integration/transmitter.rb
lib/sphinx/integration/transmitter_job.rb
spec/jobs/transmitter_job_spec.rb
spec/spec_helper.rb
spec/sphinx/integration/buffered_transmitter_spec.rb
spec/sphinx/integration/transmitter_spec.rb

https://jira.railsc.ru/browse/GOODS-1524

feat: add buffered_transmitter

---

Gemfile
lib/sphinx/integration/tasks.rake

https://jira.railsc.ru/browse/BPC-13333

feature: configure log device

---

lib/sphinx/integration.rb
lib/sphinx/integration/helper.rb
lib/sphinx/integration/replayer_job.rb
lib/sphinx/integration/version.rb
spec/sphinx/integration/helper_spec.rb

Для ускорения общей индексации,а то у нас этот этап для товаров около часа длится

feature: delayed replay soft delete log

---

lib/sphinx/integration/tasks.rake
lib/sphinx/integration/version.rb

https://jira.railsc.ru/browse/BPC-13333

 feature: configure log for sphinx:rebuild

---

lib/sphinx/integration/transmitter.rb
lib/sphinx/integration/version.rb

https://jira.railsc.ru/browse/BPC-13630

 fix: do not calculate sphinx_offset in cycle

---

lib/sphinx/integration/fast_facet.rb
lib/sphinx/integration/version.rb

https://jira.railsc.ru/browse/BPC-14812

fix: dont override ts_args in fast_facet

---

Appraisals
Gemfile
dip.yml
lib/sphinx/integration/extensions/thinking_sphinx/configuration.rb
lib/sphinx/integration/extensions/thinking_sphinx/property.rb
lib/sphinx/integration/railtie.rb
sphinx-integration.gemspec

Запатчил, чтобы уже начать переход на новые рельсы)

feature: rails4.2 support

---

Gemfile
lib/sphinx/integration/helper.rb
lib/sphinx/integration/mysql/query_log.rb
lib/sphinx/integration/mysql/replayer.rb
lib/sphinx/integration/replayer_job.rb
lib/sphinx/integration/statements/plain.rb
spec/sphinx/integration/helper_spec.rb
spec/sphinx/integration/mysql/query_log_spec.rb
spec/sphinx/integration/mysql/replayer_spec.rb
spec/sphinx/integration/statements/plain_spec.rb

https://jira.railsc.ru/browse/GOODS-2176

fix: split replayer by index name

---

lib/sphinx/integration/extensions/thinking_sphinx/index.rb
lib/sphinx/integration/mysql/replayer.rb
lib/sphinx/integration/statements.rb
lib/sphinx/integration/statements/core.rb
lib/sphinx/integration/statements/plain.rb
lib/sphinx/integration/transmitter.rb
spec/sphinx/integration/mysql/replayer_spec.rb
spec/sphinx/integration/statements/plain_spec.rb
spec/sphinx/integration/transmitter_spec.rb

https://jira.railsc.ru/browse/GOODS-2270

feature: replay transmitter update from rt index

---

.drone.yml
Gemfile
lib/sphinx/integration/extensions/thinking_sphinx/index.rb
lib/sphinx/integration/helper.rb
lib/sphinx/integration/statements/core.rb
lib/sphinx/integration/statements/distributed.rb
lib/sphinx/integration/statements/plain.rb
lib/sphinx/integration/statements/rt.rb
lib/sphinx/integration/transmitter.rb
spec/sphinx/integration/extensions/thinking_sphinx/index_spec.rb
spec/sphinx/integration/helper_spec.rb
spec/sphinx/integration/transmitter_spec.rb

https://jira.railsc.ru/browse/GOODS-2250

feature: delete prev rt rows when indexing

---

lib/sphinx/integration/helper.rb
spec/internal/app/models/model_with_rt.rb
spec/sphinx/integration/helper_spec.rb

https://jira.railsc.ru/browse/GOODS-2439

feature: wait index rotation

---

lib/sphinx/integration/helper_adapters/remote.rb
spec/sphinx/integration/helper_adapters/remote_spec.rb

https://jira.railsc.ru/browse/PC4-25477
нужна ветка **decresase-compress-level**

feature: decrease compress level for indexes copying

---

lib/sphinx/integration/transmitter.rb
spec/sphinx/integration/transmitter_spec.rb

https://jira.railsc.ru/browse/GOODS-2445

feature: use retransmit instead of update

---

lib/sphinx/integration/extensions/thinking_sphinx/active_record.rb
lib/sphinx/integration/transmitter.rb
spec/sphinx/integration/buffered_transmitter_spec.rb
spec/sphinx/integration/extensions/thinking_sphinx/active_record_spec.rb
spec/sphinx/integration/transmitter_spec.rb

https://jira.railsc.ru/browse/GOODS-2512

fix: do not use find in batches when id present

---

Appraisals
Gemfile
dip.yml
lib/sphinx/integration/helper.rb
lib/sphinx/integration/helper_adapters/local.rb
lib/sphinx/integration/helper_adapters/remote.rb
lib/sphinx/integration/spec/support/thinking_sphinx.rb
spec/sphinx/integration/helper_adapters/local_spec.rb
spec/sphinx/integration/helper_adapters/remote_spec.rb
spec/sphinx/integration/helper_spec.rb

https://jira.railsc.ru/browse/BPC-18010

feature: gentle rotation

---

lib/sphinx/integration/extensions/thinking_sphinx/index/builder.rb
spec/sphinx/integration/extensions/thinking_sphinx/index/builder_spec.rb

https://jira.railsc.ru/browse/GOODS-2607

feature: ability to rename cte

---

lib/sphinx/integration.rb
lib/sphinx/integration/constants.rb
lib/sphinx/integration/version.rb

https://jira.railsc.ru/browse/BPC-18272
Мне такое значение в сфинксе очень надо. Я посмотрел мельком, есть места где используется
https://github.com/abak-press/apress-demands/blob/bf5a646493cc9f00c763187bd6c38dcf0785b5d2/app/models/apress/demands/tender.rb#L233

feature: add INT_INFINITY_VAL default constant

---

.drone.yml
lib/sphinx/integration/helper_adapters/remote.rb
spec/sphinx/integration/helper_adapters/remote_spec.rb

https://jira.railsc.ru/browse/BPC-18868

feature: add ionice for rsync command

---

lib/sphinx/integration/extensions/riddle/configuration/searchd.rb

https://jira.railsc.ru/browse/BPC-18802

feature: add more configuration options

---

lib/sphinx/integration/extensions/riddle/client.rb

https://jira.railsc.ru/browse/BPC-18936

fix: add timeout for reading from socket

---

lib/sphinx/integration/extensions/riddle/client.rb

https://jira.railsc.ru/browse/BPC-18936

fix: decrease timeout, freeze strings and fix some misspells

---

lib/sphinx/integration/extensions/riddle/client.rb
spec/sphinx/integration/extensions/thinking_sphinx/riddle/client_spec.rb

https://jira.railsc.ru/browse/BPC-18995

fix: partial nonblock reading + test coverage

---

.rspec
lib/sphinx/integration/helper.rb
lib/sphinx/integration/helper_adapters/remote.rb
lib/sphinx/integration/version.rb
spec/sphinx/integration/helper_adapters/remote_spec.rb
spec/sphinx/integration/helper_spec.rb

https://jira.railsc.ru/browse/BPC-19000

feature: remove disable/enable host before rotation

---

.drone.yml
Appraisals
lib/sphinx/integration/helper.rb
lib/sphinx/integration/helper_adapters/remote.rb
lib/sphinx/integration/version.rb
spec/sphinx/integration/helper_adapters/remote_spec.rb
spec/sphinx/integration/helper_spec.rb

https://jira.railsc.ru/browse/BPC-19000

fix: wait before the previous node has rotated 

---

lib/sphinx/integration/extensions/riddle/client.rb
lib/sphinx/integration/helper_adapters/remote.rb
lib/sphinx/integration/server.rb
lib/sphinx/integration/server_pool.rb
lib/sphinx/integration/server_status.rb
spec/sphinx/integration/helper_adapters/remote_spec.rb

https://jira.railsc.ru/browse/BPC-19494

feature: add busy status for server, search consider busyness

---

lib/sphinx/integration/helper.rb
lib/sphinx/integration/railtie.rb

https://jira.railsc.ru/browse/PC4-27616

feat(sphinx_index): added mailer notification after index

---

lib/sphinx/integration/helper.rb
lib/sphinx/integration/railtie.rb
lib/sphinx/integration/version.rb

[#24424](https://github.com/abak-press/pulscen/pull/24424)

Merge pc-january-1 into master and Release 7.16.0

---

lib/sphinx/integration/extensions/thinking_sphinx/configuration.rb
lib/sphinx/integration/statements/distributed.rb
lib/sphinx/integration/statements/rt.rb
lib/sphinx/integration/version.rb
spec/sphinx/integration/extensions/thinking_sphinx/index_spec.rb
spec/sphinx/integration/helper_spec.rb
spec/sphinx/integration/statements/rt_spec.rb

[#24608](https://github.com/abak-press/pulscen/pull/24608)

Merge vip-truncate into master and Release 7.16.1

---

lib/sphinx/integration/extensions/thinking_sphinx/configuration.rb
lib/sphinx/integration/extensions/thinking_sphinx/index.rb
lib/sphinx/integration/helper.rb
lib/sphinx/integration/helper_adapters/remote.rb
lib/sphinx/integration/railtie.rb
lib/sphinx/integration/statements/distributed.rb
lib/sphinx/integration/statements/rt.rb
spec/sphinx/integration/helper_adapters/remote_spec.rb
spec/sphinx/integration/helper_spec.rb

https://jira.railsc.ru/browse/PC4-28154

feat: move truncate into main block

---

lib/sphinx/integration/extensions/thinking_sphinx/configuration.rb
lib/sphinx/integration/extensions/thinking_sphinx/index.rb
lib/sphinx/integration/helper.rb
lib/sphinx/integration/helper_adapters/remote.rb
lib/sphinx/integration/railtie.rb
lib/sphinx/integration/statements/distributed.rb
lib/sphinx/integration/statements/rt.rb
lib/sphinx/integration/version.rb
spec/sphinx/integration/helper_adapters/remote_spec.rb
spec/sphinx/integration/helper_spec.rb

move truncate into main block
you should set vip_client_read_timeout in the project

MERGE: vip-truncate into master and Release 7.17.0

---

.drone.yml
.rspec
Appraisals
Gemfile
dip.yml
lib/sphinx/integration.rb
lib/sphinx/integration/extensions/thinking_sphinx/configuration.rb
lib/sphinx/integration/extensions/thinking_sphinx/index.rb
lib/sphinx/integration/helper_adapters/remote.rb
lib/sphinx/integration/optimize_rt_index_job.rb
lib/sphinx/integration/railtie.rb
lib/sphinx/integration/statements/rt.rb
spec/jobs/optimize_rt_index_job_spec.rb
spec/spec_helper.rb
spec/sphinx/integration/extensions/thinking_sphinx/configuration_spec.rb
spec/sphinx/integration/extensions/thinking_sphinx/index_spec.rb
spec/sphinx/integration/statements/rt_spec.rb
sphinx-integration.gemspec

https://jira.railsc.ru/browse/BPC-20841

feat: optimize rt indexes job

---

lib/sphinx/integration/optimize_rt_index_job.rb
spec/jobs/optimize_rt_index_job_spec.rb

после отправки OPTIMIZE , SHOW THREADS не сразу показывает тред SYSTEM OPTIMIZE, добавил задержку

fix: use read instead write and fix notifications

---

lib/sphinx/integration/optimize_rt_index_job.rb
lib/sphinx/integration/version.rb

при подключении ничего делать не надо

feature(optimize rt idxs): disable info notification to telegram
